from pathlib import Path
import re
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]

LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})(.*)$")
INLINE_CODE_RE = re.compile(r"(`+)(.*?)\1")
EXTERNAL_PREFIXES = (
    "http://",
    "https://",
    "mailto:",
    "ftp://",
    "data:",
)

# Generated by CI rather than committed to the repository.
ALLOWED_GENERATED = {
    "paper/main.pdf",
}


def parse_target(raw: str) -> str:
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        target = target[1 : target.index(">")]
    elif " " in target:
        # Markdown permits an optional title after the target.
        target = target.split(None, 1)[0]
    return unquote(target.strip())


def is_external_or_anchor(target: str) -> bool:
    lowered = target.lower()
    return (
        not target
        or target.startswith("#")
        or target.startswith("/")
        or lowered.startswith(EXTERNAL_PREFIXES)
    )


def normalize_repo_relative(markdown_file: Path, target: str) -> tuple[Path, str]:
    path_part = target.split("#", 1)[0].split("?", 1)[0]
    resolved = (markdown_file.parent / path_part).resolve()
    try:
        relative = resolved.relative_to(ROOT).as_posix()
    except ValueError:
        return resolved, ""
    return resolved, relative


def rendered_prose(text: str) -> str:
    """Return Markdown prose with fenced and inline code removed.

    Link-like examples inside literal code must not be treated as repository links.
    """
    output: list[str] = []
    fence_marker: str | None = None

    for line in text.splitlines():
        stripped = line.strip()
        if fence_marker is not None:
            if (
                stripped
                and stripped[0] == fence_marker[0]
                and set(stripped) == {fence_marker[0]}
                and len(stripped) >= len(fence_marker)
            ):
                fence_marker = None
            continue

        match = FENCE_RE.match(line)
        if match:
            fence_marker = match.group(1)
            continue

        output.append(INLINE_CODE_RE.sub("", line))

    return "\n".join(output)


missing: list[str] = []
checked = 0

for markdown_file in sorted(ROOT.rglob("*.md")):
    if ".git" in markdown_file.parts:
        continue

    text = rendered_prose(markdown_file.read_text(encoding="utf-8"))
    for match in LINK_RE.finditer(text):
        target = parse_target(match.group(1))
        if is_external_or_anchor(target):
            continue

        resolved, relative = normalize_repo_relative(markdown_file, target)
        if not relative:
            continue
        if relative in ALLOWED_GENERATED:
            continue

        checked += 1
        if not resolved.exists():
            source = markdown_file.relative_to(ROOT).as_posix()
            missing.append(f"{source}: {target}")

if missing:
    raise SystemExit(
        "Broken repository-relative Markdown links:\n" + "\n".join(missing)
    )

print(f"Markdown links OK: {checked} rendered repository-relative targets resolved.")
