from pathlib import Path
import re
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]

LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
LINKED_IMAGE_OUTER_RE = re.compile(r"\[!\[[^\]]*\]\([^)]+\)\]\(([^)]+)\)")
REFERENCE_DEF_RE = re.compile(r"^ {0,3}\[(?!\^)[^\]]+\]:\s*(?:<([^>]+)>|(\S+))", re.MULTILINE)
FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
CLOSING_FENCE_RE = re.compile(r"^ {0,3}([`~]{3,})[ \t]*$")
INLINE_CODE_RE = re.compile(r"(`+)(.*?)\1")
EXTERNAL_PREFIXES = (
    "http://",
    "https://",
    "mailto:",
    "ftp://",
    "data:",
)

# Generated by CI rather than committed to the repository.
ALLOWED_GENERATED = {
    "paper/main.pdf",
}


def parse_target(raw: str) -> str:
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        target = target[1 : target.index(">")]
    elif " " in target:
        # Markdown permits an optional title after the target.
        target = target.split(None, 1)[0]
    return unquote(target.strip())


def is_external_or_anchor(target: str) -> bool:
    lowered = target.lower()
    return (
        not target
        or target.startswith("#")
        or target.startswith("/")
        or lowered.startswith(EXTERNAL_PREFIXES)
    )


def normalize_repo_relative(markdown_file: Path, target: str) -> tuple[Path, str | None]:
    path_part = target.split("#", 1)[0].split("?", 1)[0]
    resolved = (markdown_file.parent / path_part).resolve()
    try:
        relative = resolved.relative_to(ROOT).as_posix()
    except ValueError:
        return resolved, None
    return resolved, relative


def closes_fence(line: str, marker: str) -> bool:
    match = CLOSING_FENCE_RE.match(line)
    if not match:
        return False
    candidate = match.group(1)
    return candidate[0] == marker[0] and len(candidate) >= len(marker)


def rendered_prose(text: str) -> str:
    """Return Markdown prose with fenced and inline code removed.

    Link-like examples inside literal code must not be treated as repository links.
    CommonMark fenced blocks may be indented by at most three spaces.
    """
    output: list[str] = []
    fence_marker: str | None = None

    for line in text.splitlines():
        if fence_marker is not None:
            if closes_fence(line, fence_marker):
                fence_marker = None
            continue

        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            info = match.group(2)
            # A backtick fence opener cannot contain another backtick in its info string.
            if marker[0] != "`" or "`" not in info:
                fence_marker = marker
                continue

        output.append(INLINE_CODE_RE.sub("", line))

    return "\n".join(output)


def iter_targets(text: str):
    """Yield inline/image targets, linked-image outer targets, and reference definitions."""
    for match in LINK_RE.finditer(text):
        yield match.group(1)
    # LINK_RE sees the inner image in [![alt](image.svg)](page.md) but not the outer
    # destination because the link label contains nested Markdown. Validate it separately.
    for match in LINKED_IMAGE_OUTER_RE.finditer(text):
        yield match.group(1)
    # A reference-style usage resolves through its definition, so validating every local
    # definition target covers both normal and image reference forms without reimplementing
    # GitHub's full reference-label matching algorithm. GitHub footnotes use [^id]: and are
    # intentionally excluded because their body is prose, not a link destination.
    for match in REFERENCE_DEF_RE.finditer(text):
        yield match.group(1) or match.group(2)


missing: list[str] = []
checked = 0

for markdown_file in sorted(ROOT.rglob("*.md")):
    if ".git" in markdown_file.parts:
        continue

    text = rendered_prose(markdown_file.read_text(encoding="utf-8"))
    for raw_target in iter_targets(text):
        target = parse_target(raw_target)
        if is_external_or_anchor(target):
            continue

        source = markdown_file.relative_to(ROOT).as_posix()
        resolved, relative = normalize_repo_relative(markdown_file, target)
        if relative is None:
            missing.append(f"{source}: relative target escapes repository root: {target}")
            continue
        if relative in ALLOWED_GENERATED:
            continue

        checked += 1
        if not resolved.exists():
            missing.append(f"{source}: {target}")

if missing:
    raise SystemExit(
        "Broken repository-relative Markdown links:\n" + "\n".join(missing)
    )

print(
    f"Markdown links OK: {checked} rendered repository-relative inline, linked-image, "
    "and reference-definition targets resolved."
)
